//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDAU
    {
        public int MA_HDAU { get; set; }
        public int MA_MH { get; set; }
        public Nullable<int> SOLUONG_MH { get; set; }
    
        public virtual HOADONANUONG HOADONANUONG { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
