//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDDC
    {
        public int MA_HDDC { get; set; }
        public int MA_CD { get; set; }
        public Nullable<int> SOLUONG_CD { get; set; }
    
        public virtual CHUYENDI CHUYENDI { get; set; }
        public virtual HOADONDICHUYEN HOADONDICHUYEN { get; set; }
    }
}
