//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using QuanLyKhachSan.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPHONG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIPHONG()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public int MA_LP { get; set; }
        private string _TEN_LP;
        public string TEN_LP { get => _TEN_LP; set { _TEN_LP = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DONGIA_LP;
        public Nullable<decimal> DONGIA_LP { get => _DONGIA_LP; set { _DONGIA_LP = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
