//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKS_IS201Entities : DbContext
    {
        public QLKS_IS201Entities()
            : base("name=QLKS_IS201Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_HDAU> CHITIET_HDAU { get; set; }
        public virtual DbSet<CHITIET_HDDC> CHITIET_HDDC { get; set; }
        public virtual DbSet<CHITIET_HDLT> CHITIET_HDLT { get; set; }
        public virtual DbSet<CHUYENDI> CHUYENDIs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOADONANUONG> HOADONANUONGs { get; set; }
        public virtual DbSet<HOADONDICHUYEN> HOADONDICHUYENs { get; set; }
        public virtual DbSet<HOADONGIATUI> HOADONGIATUIs { get; set; }
        public virtual DbSet<HOADONLUUTRU> HOADONLUUTRUs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIGIATUI> LOAIGIATUIs { get; set; }
        public virtual DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public virtual DbSet<LUOTGIATUI> LUOTGIATUIs { get; set; }
        public virtual DbSet<MATHANG> MATHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
