//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Model
{
    using QuanLyKhachSan.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }

        private int _MA_TK;
        public int MA_TK { get => _MA_TK; set { _MA_TK = value; OnPropertyChanged(); } }
        private string _TENDANGNHAP_TK;
        public string TENDANGNHAP_TK { get => _TENDANGNHAP_TK; set { _TENDANGNHAP_TK = value; OnPropertyChanged(); } }
        private string _MATKHAU_TK;
        public string MATKHAU_TK { get => _MATKHAU_TK; set { _MATKHAU_TK = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
