//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAONAM
    {
        public int MA_BCN { get; set; }
        public Nullable<System.DateTime> THOIGIANLAP_BCN { get; set; }
        public Nullable<int> NAM_BCN { get; set; }
        public Nullable<decimal> TONGDOANHTHU_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG1_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG2_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG3_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG4_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG5_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG6_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG7_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG8_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG9_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG10_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG11_BCN { get; set; }
        public Nullable<decimal> DOANHTHUTHANG12_BCN { get; set; }
    }
}
