//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODICHVU
    {
        public int MA_BCDV { get; set; }
        public Nullable<System.DateTime> THOIGIANLAP_BCDV { get; set; }
        public Nullable<decimal> TONGDOANHTHU_BCDV { get; set; }
        public Nullable<decimal> DOANHTHULUUTRU_BCDV { get; set; }
        public Nullable<decimal> DOANHTHUANUONG_BCDV { get; set; }
        public Nullable<decimal> DOANHTHUGIATUI_BCDV { get; set; }
        public Nullable<decimal> DOANHTHUDICHUYEN_BCDV { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU_BCDV { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC_BCDV { get; set; }
    }
}
