//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATPHONG
    {
        public int MA_DP { get; set; }
        public int MA_PHONG { get; set; }
        public int MA_NV { get; set; }
        public int MA_KH { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU_DP { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC_DP { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
