//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDLT
    {
        public int MA_HDLT { get; set; }
        public int MA_PHONG { get; set; }
        public Nullable<System.DateTime> THOIGIANNHAN_PHONG { get; set; }
        public Nullable<System.DateTime> THOIGIANTRA_PHONG { get; set; }
    
        public virtual HOADONLUUTRU HOADONLUUTRU { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
