//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MA_HD { get; set; }
        public Nullable<int> MA_HDAU { get; set; }
        public Nullable<int> MA_HDGU { get; set; }
        public int MA_HDLT { get; set; }
        public Nullable<int> MA_HDDC { get; set; }
        public int MA_NV { get; set; }
        public int MA_KH { get; set; }
        public Nullable<System.DateTime> THOIGIANLAP_HD { get; set; }
        public Nullable<bool> TINHTRANG_HD { get; set; }
        public Nullable<decimal> TRIGIA_HD { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual HOADONLUUTRU HOADONLUUTRU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
