//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONANUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONANUONG()
        {
            this.CHITIET_HDAU = new HashSet<CHITIET_HDAU>();
        }
    
        public int MA_HDAU { get; set; }
        public System.DateTime THOIGIANLAP_HDAU { get; set; }
        public Nullable<bool> TINHTRANG_HDAU { get; set; }
        public Nullable<decimal> TRIGIA_HDAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDAU> CHITIET_HDAU { get; set; }
    }
}
